/**
 * Verification proves a version. Apply changes one.
 *
 * Staged verification copies the project, applies the proposal to the copy, and
 * runs the project's own checks. What comes back is a statement about a *version*
 * of a file -- but nothing recorded which version, so between the check and the
 * write the file could change: a build regenerating it, an editor autosaving,
 * the developer typing.
 *
 * The obvious defence does not work. `#patchFile` already refuses when the
 * `find` anchor is missing, so the failure mode is not a missing anchor -- it is a
 * *newer* file that still contains the same anchor. The edit applies cleanly,
 * parses cleanly, and lands in a version of the code nobody verified.
 *
 * So the preimage is hashed before verification and compared against the bytes
 * actually read, through the validated descriptor, immediately before writing.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { verifyProposals } from '../src/act/verify.mjs';
import { Applier } from '../src/act/apply.mjs';
import { sha256Of, shortHash } from '../src/act/hashes.mjs';

/** A project whose verification command always passes, so the gate can open. */
function project({ body = 'const MARKER = 1;\nmodule.exports = { MARKER };\n' } = {}) {
  const root = mkdtempSync(join(tmpdir(), 'wd-occ-'));
  mkdirSync(join(root, 'src'), { recursive: true });
  writeFileSync(join(root, 'src', 'a.js'), body, 'utf8');
  writeFileSync(join(root, 'package.json'), '{"name":"occ"}\n', 'utf8');

  const check = mkdtempSync(join(tmpdir(), 'wd-check-'));
  writeFileSync(join(check, 'check.cjs'), 'process.exit(0);\n', 'utf8');
  return { root, checkArgv: [process.execPath, join(check, 'check.cjs')] };
}

const applierFor = (root) =>
  new Applier({ projectRoot: root, dataDir: join(root, '.watchdog'), autonomy: 'autonomous', allowlist: [] });

const proposal = [{ path: 'src/a.js', find: 'const MARKER = 1;', replace: 'const MARKER = 2;' }];

/* ------------------------------------------------------------------ *
 * The reproduction
 * ------------------------------------------------------------------ */

test('a file changed after verification is not written to', async () => {
  const { root, checkArgv } = project();
  const target = join(root, 'src', 'a.js');

  // 1. Verify. This passes, and tells us which version it checked.
  const v = await verifyProposals({ projectRoot: root, files: proposal, verifyCfg: { command: checkArgv, timeoutMs: 60_000 } });
  assert.equal(v.verdict, 'pass', `setup failed: ${v.why}`);
  assert.ok(v.preimages?.length, 'verification did not record a preimage');

  // 2. The file changes -- a build regenerates it, an editor autosaves. Note that
  //    the anchor is deliberately still present, so every existing check passes.
  writeFileSync(target, 'const MARKER = 1;\n// regenerated by the build\nmodule.exports = { MARKER };\n', 'utf8');

  // 3. Apply, with the preimage from step 1.
  const res = applierFor(root).apply(
    { kind: 'patch-file', ...proposal[0], expectPreimage: v.preimages[0].sha256 },
    { cwd: root, source: 'llm' },
  );

  assert.equal(res.status, 'stale', `expected stale, got ${JSON.stringify(res)}`);
  assert.equal(res.code, 'stale_preimage');
  assert.match(res.why, /changed after it was verified/i);
  assert.match(readFileSync(target, 'utf8'), /regenerated by the build/, 'the newer version was overwritten');
  assert.ok(!readFileSync(target, 'utf8').includes('MARKER = 2'), 'the edit landed in a file nobody verified');
});

test('without the change, the same proposal applies normally', async () => {
  // The control. Refusing everything would pass the test above.
  const { root, checkArgv } = project();
  const v = await verifyProposals({ projectRoot: root, files: proposal, verifyCfg: { command: checkArgv, timeoutMs: 60_000 } });
  assert.equal(v.verdict, 'pass', v.why);

  const res = applierFor(root).apply(
    { kind: 'patch-file', ...proposal[0], expectPreimage: v.preimages[0].sha256 },
    { cwd: root, source: 'llm' },
  );
  assert.equal(res.status, 'applied', JSON.stringify(res));
  assert.match(readFileSync(join(root, 'src', 'a.js'), 'utf8'), /MARKER = 2/);
});

test('the preimage is the content that was verified, not the content after it', async () => {
  const { root, checkArgv } = project();
  const original = readFileSync(join(root, 'src', 'a.js'), 'utf8');
  const v = await verifyProposals({ projectRoot: root, files: proposal, verifyCfg: { command: checkArgv, timeoutMs: 60_000 } });
  assert.equal(v.preimages[0].sha256, sha256Of(original), 'the preimage is not the version that was checked');
});

test('a preimage for a different file does not satisfy the check', async () => {
  const { root, checkArgv } = project();
  const v = await verifyProposals({ projectRoot: root, files: proposal, verifyCfg: { command: checkArgv, timeoutMs: 60_000 } });

  const res = applierFor(root).apply(
    { kind: 'patch-file', ...proposal[0], expectPreimage: sha256Of('some other file entirely') },
    { cwd: root, source: 'llm' },
  );
  assert.equal(res.status, 'stale');
});

test('an omitted preimage applies, because rule-driven fixes have no verify step', async () => {
  // The precondition is optional on purpose. A deterministic rule fix is reviewed
  // by the rule's author and does not go through staged verification, so requiring
  // a hash there would break every rule fix with nothing to check against.
  const { root } = project();
  const res = applierFor(root).apply({ kind: 'patch-file', ...proposal[0] }, { cwd: root, source: 'rule' });
  assert.equal(res.status, 'applied', JSON.stringify(res));
});

test('a stale refusal leaves nothing journalled as applied', async () => {
  const { root, checkArgv } = project();
  const target = join(root, 'src', 'a.js');
  const v = await verifyProposals({ projectRoot: root, files: proposal, verifyCfg: { command: checkArgv, timeoutMs: 60_000 } });
  writeFileSync(target, 'const MARKER = 1;\n// changed\nmodule.exports = { MARKER };\n', 'utf8');

  const a = applierFor(root);
  a.apply({ kind: 'patch-file', ...proposal[0], expectPreimage: v.preimages[0].sha256 }, { cwd: root, source: 'llm' });
  assert.equal(a.listJournal().filter((j) => j.outcome === 'ok').length, 0, 'a stale refusal was journalled as applied');
});

/* ------------------------------------------------------------------ *
 * Through the watcher, where the precondition has to be threaded
 * ------------------------------------------------------------------ */

test('the watcher passes the verified preimage through, and a file that moves mid-verification stops it', async () => {
  // The tests above prove the applier honours `expectPreimage`. Only this one
  // proves the watcher supplies it -- and an earlier mutation of a single line in
  // this path passed the entire suite, so the wiring needs its own coverage.
  //
  // The file is changed by the verification command itself. Sleeping and
  // rewriting from the test does not work: the change has to land after the staged
  // copy was taken, and any sleep either lands before staging -- so the copy
  // already has it and the hash matches -- or is a race. Having the check script
  // do it is exact.
  const { Watcher } = await import('../src/core/watcher.mjs');
  const { loadConfig } = await import('../src/core/config.mjs');
  const { stubAnswering } = await import('./helpers/stub-cli.mjs');

  const { root } = project();
  const target = join(root, 'src', 'a.js');

  // The check passes, and while running it rewrites the *real* file -- a build
  // step would do exactly this. The anchor survives, so only the hash notices.
  const checkDir = mkdtempSync(join(tmpdir(), 'wd-check-'));
  const moved = 'const MARKER = 1;\n// regenerated mid-verification\nmodule.exports = { MARKER };\n';
  writeFileSync(
    join(checkDir, 'check.cjs'),
    "require('fs').writeFileSync(" + JSON.stringify(target) + ', ' + JSON.stringify(moved) + ');\nprocess.exit(0);\n',
    'utf8',
  );
  const checkArgv = [process.execPath, join(checkDir, 'check.cjs')];

  const stub = stubAnswering(
    JSON.stringify({
      verdict: 'problem',
      confidence: 0.95,
      summary: 'MARKER should be 2',
      fix: { description: 'd', files: [{ path: 'src/a.js', find: 'const MARKER = 1;', replace: 'const MARKER = 2;' }] },
    }),
  );

  const base = loadConfig({ cwd: root, projectRoot: root });
  const watcher = new Watcher({
    ...base,
    projectRoot: root,
    autonomy: 'autonomous',
    analyze: {
      ...base.analyze,
      llm: { enabled: true, cli: stub.cmd, model: null, timeoutMs: 60_000, minSeverity: 'low', maxInvocationsPerSession: 5 },
    },
    verify: { command: checkArgv, timeoutMs: 60_000 },
    paths: { data: join(root, '.watchdog') },
  });

  const seen = [];
  watcher.on('needs-human', (rec) => seen.push(rec));
  watcher.on('finding-updated', (rec) => seen.push(rec));

  await watcher.ingest('ZorblaxError: marker drift\n    at run (/app/src/a.js:1:1)', {
    sessionId: 's1',
    cwd: root,
    shell: 'powershell',
  });

  const deadline = Date.now() + 40_000;
  while (Date.now() < deadline && !seen.some((r) => r.advisor?.verification || r.advisor?.requiresHuman)) {
    await new Promise((r) => setTimeout(r, 50));
  }
  await new Promise((r) => setTimeout(r, 400));

  const body = readFileSync(target, 'utf8');
  assert.ok(!body.includes('MARKER = 2'), `the edit landed in a file nobody verified: ${body}`);
  assert.match(body, /regenerated mid-verification/, 'the newer version was overwritten');
});

void dirname;
void execFileSync;
/* ------------------------------------------------------------------ *
 * The hash itself
 * ------------------------------------------------------------------ */

test('the hash distinguishes versions that share an anchor', () => {
  // This is the case the anchor check cannot see.
  const before = 'const MARKER = 1;\nmodule.exports = { MARKER };\n';
  const after = 'const MARKER = 1;\n// a build added this\nmodule.exports = { MARKER };\n';
  assert.ok(before.includes('const MARKER = 1;'));
  assert.ok(after.includes('const MARKER = 1;'), 'the anchor must be in both for this to mean anything');
  assert.notEqual(sha256Of(before), sha256Of(after));
});

test('the hash is stable for identical content', () => {
  assert.equal(sha256Of('same'), sha256Of('same'));
  assert.equal(sha256Of('a'), sha256Of(Buffer.from('a', 'utf8')));
  assert.notEqual(sha256Of('a'), sha256Of('b'));
});

test('shortHash is for messages only and is never compared', () => {
  const full = sha256Of('anything');
  assert.equal(full.length, 64);
  assert.equal(shortHash(full), full.slice(0, 12) + '...');
  // Two hashes sharing a 12-character prefix would compare equal in short form,
  // which is exactly why nothing compares short forms.
  assert.notEqual(shortHash(sha256Of('a')), shortHash(sha256Of('b')));
});

/* ------------------------------------------------------------------ *
 * Multiple files
 * ------------------------------------------------------------------ */

test('each file gets its own preimage, and one stale file does not block the other', async () => {
  const { root, checkArgv } = project();
  writeFileSync(join(root, 'src', 'b.js'), 'const OTHER = 1;\nmodule.exports = { OTHER };\n', 'utf8');

  const files = [
    { path: 'src/a.js', find: 'const MARKER = 1;', replace: 'const MARKER = 2;' },
    { path: 'src/b.js', find: 'const OTHER = 1;', replace: 'const OTHER = 2;' },
  ];
  const v = await verifyProposals({ projectRoot: root, files, verifyCfg: { command: checkArgv, timeoutMs: 60_000 } });
  assert.equal(v.verdict, 'pass', v.why);
  assert.equal(v.preimages.length, 2);
  assert.notEqual(v.preimages[0].sha256, v.preimages[1].sha256, 'two different files share a preimage');

  // Only the first file moves.
  writeFileSync(join(root, 'src', 'a.js'), 'const MARKER = 1;\n// moved\nmodule.exports = { MARKER };\n', 'utf8');

  const a = applierFor(root);
  const pre = new Map(v.preimages.map((p) => [p.path, p.sha256]));
  const r1 = a.apply({ kind: 'patch-file', ...files[0], expectPreimage: pre.get('src/a.js') }, { cwd: root, source: 'llm' });
  const r2 = a.apply({ kind: 'patch-file', ...files[1], expectPreimage: pre.get('src/b.js') }, { cwd: root, source: 'llm' });

  assert.equal(r1.status, 'stale', 'the changed file should have been refused');
  assert.equal(r2.status, 'applied', 'the unchanged file should still apply');
});

void dirname;
void execFileSync;